import './globals.css'
import type { Metadata } from 'next'

import Navbar from '@/components/navbar'
import AuthProvider from '@/components/auth-provider'

import { DM_Sans } from 'next/font/google'
const default_font = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={default_font.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
